apiVersion: v2
name: pagopa-biz-events-sync-nodo
description: Scheduled microservice that re-elaborates failed biz-events
type: application
version: 0.36.0
appVersion: 0.1.4-7-PAGOPA-3170
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
