apiVersion: v2
name: pagopa-biz-events-sync-nodo
description: Scheduled microservice that re-elaborates failed biz-events
type: application
version: 0.2.0
appVersion: 0.0.0-2-PIDM-265
dependencies:
  - name: microservice-chart
    version: 7.1.1
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
