apiVersion: v2
name: pagopa-biz-events-sync-nodo
description: Scheduled microservice that re-elaborates failed biz-events
type: application
version: 0.77.0
appVersion: 0.2.1
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
